# FeedbackPlugin Configuration

discord:
  # Paste your Discord webhook URL here
  webhook-url: "https://discord.com/api/webhooks/1488639027237359828/uFfs6Hw9ymNZqUkOKfaSylJTRL-PchxdVeetrqegmdZL4i4YJaI3x5bBg5eSGeGykYsl"

# Cooldown in seconds between feedback submissions per player
cooldown-seconds: 86400

# Maximum character length of a feedback message
max-message-length: 500
